#!/bin/sh

# You may find this shell script helpful.

java -mx200m -cp classes \
  cs114.assignments.LanguageModelTester \
  -model cs114.langmodel.BigramsMini \
  -data      data \
  -train     big-train-data.txt \
  -test      test-data-no-oov.txt \
  -showguesses       false \
  -jumble       true \
  -baselines true \
  -generate  true \
  $@
